# Here you put the channels you want to get the jobs from
# Each channel should be on a separate line
# Example:
# @channel1
# @channel2
# @channel3
# You can get the channel username from the channel info
# 
